-- Common ingredients
INSERT INTO ingredients (name) VALUES
    ('Salt'),
    ('Black Pepper'),
    ('Olive Oil'),
    ('Garlic'),
    ('Onion'),
    ('Butter'),
    ('All-Purpose Flour'),
    ('Sugar'),
    ('Eggs'),
    ('Milk'),
    ('Chicken'),
    ('Beef'),
    ('Tomatoes'),
    ('Potatoes'),
    ('Carrots'),
    ('Celery'),
    ('Rice'),
    ('Pasta'),
    ('Cheese'),
    ('Lemon'),
    ('Vegetable Oil'),
    ('Soy Sauce'),
    ('Ginger'),
    ('Paprika'),
    ('Cumin'),
    ('Oregano'),
    ('Basil'),
    ('Thyme'),
    ('Bay Leaves'),
    ('Heavy Cream')
ON CONFLICT (name) DO NOTHING;
